In [2]:
from misc_functions import get_example_params, save_gradient_images, convert_to_grayscale, get_positive_negative_saliency
from guided_backprop import GuidedBackprop
import layer_activation_with_guided_backprop
from cnn_layer_visualization import CNNLayerVisualization
import generate_class_specific_samples # import GenerateClassSpecificSamples
import models

In [9]:
import generate_regularized_class_specific_samples
import models
import importlib
import torch

importlib.reload(generate_regularized_class_specific_samples)

def remove_dropout_layers(model):
    features = torch.nn.Sequential()
    prev_layer = None
    i=0
    for layer in model.features.children():
        if isinstance(layer, torch.nn.Dropout2d):
            if not isinstance(prev_layer, torch.nn.MaxPool2d):
                continue
            layer = torch.nn.Dropout2d(0.1)
        prev_layer = layer
        features.add_module(str(i), layer);i+=1
    # assign the updated features
    model.features = features
    return model

# target_classes are from the example list from misc_functions; 
# classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

target_class = 9
model = models.__dict__['simplenet_cifar_5m_extra_pool'](num_classes=10, in_chans=3)
model = remove_dropout_layers(model)
csig = generate_regularized_class_specific_samples.RegularizedClassSpecificImageGeneration(model, target_class)
csig.generate() 

iterations: 1000, blur_freq: 4, blur_rad: 0, wd: 0.0001, clipping_value: 0.1, initial_learning_rate: 6
tensor([[ 0.2786, -0.3918, -0.2079,  0.1672,  0.5705,  0.0511,  0.3272, -0.1444,
         -0.0363, -0.6081]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[ 0.2591, -0.3929, -0.2017,  0.1692,  0.5786,  0.0575,  0.3489, -0.1680,
         -0.0412, -0.4130]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[ 0.2522, -0.3827, -0.1982,  0.1766,  0.5815,  0.0530,  0.3690, -0.1783,
         -0.0347, -0.2737]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[ 0.2365, -0.3865, -0.1936,  0.1680,  0.5873,  0.0529,  0.3863, -0.1926,
         -0.0357, -0.1662]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[ 0.2291, -0.3786, -0.1874,  0.1706,  0.5953,  0.0573,  0.4002, -0.2034,
         -0.0316, -0.0711]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[ 0.2187, -0.3794, -0.1875,  0.1708,  0.6001,  0.0584,  0.4083, -0.2008,
         -0.0306,  0.0228]], device='cuda:0', grad_

tensor([[[[-1.4321, -1.7905, -1.7227,  ..., -1.7063, -2.1168, -0.9873],
          [-1.5860, -2.1177, -2.1151,  ..., -1.9442, -1.9615, -1.5009],
          [-1.5853, -2.1170, -2.1171,  ..., -1.7904, -2.1154, -1.9453],
          ...,
          [-1.5863, -2.1176, -2.1178,  ..., -2.1167, -1.7234, -1.3970],
          [-1.7914, -1.5850, -1.4987,  ..., -2.1174, -1.7404, -1.3804],
          [-1.2948, -2.1177, -1.7392,  ..., -2.0816, -2.1176, -1.1922]],

         [[-1.0547, -1.9826, -1.5622,  ..., -2.0345, -0.9150, -1.0366],
          [-1.8074, -2.0346, -1.9108,  ..., -2.0358, -1.8575, -2.0350],
          [-1.1946, -1.9652, -1.9285,  ..., -2.0346, -2.0344, -2.0371],
          ...,
          [-1.4388, -2.0340, -1.3676,  ..., -1.8775, -2.0337, -1.6841],
          [-1.9998, -1.9299, -2.0353,  ..., -0.6331, -2.0346, -1.1419],
          [-1.8779, -1.5796, -2.0352,  ..., -1.3526, -2.0351, -1.3165]],

         [[-1.0016, -1.8031, -1.6816,  ..., -1.8021, -1.7518, -1.2289],
          [-1.8036, -1.5419, -

In [15]:
def get_example_params(example_index):
    example_list = (('../input_images/misclassified_cifar10/misclassified_7_pred_ship_actual_plane.png', 0), # !
                    ('../input_images/misclassified_cifar10/misclassified_34_pred_plane_actual_cat.png', 3),
                    ('../input_images/misclassified_cifar10/misclassified_18_pred_deer_actual_cat.png', 3))
    target_class = example_list[example_index][1]
    return target_class

get_example_params(1)

3

In [11]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.base import BaseEstimator
import numpy as np

class ImageGeneratorEstimator(BaseEstimator):
    def __init__(self, blur_freq=4, blur_rad=1, wd=0.0001, clipping_value=0.1):
        self.blur_freq = blur_freq
        self.blur_rad = blur_rad
        self.wd = wd
        self.clipping_value = clipping_value
        # Initialize your image generation model here

    def fit(self, X, y=None):
        # Run your image generation process here using the instance's parameters
        # Instead of training, generate images and evaluate them based on your criteria
        return self

    def score(self, X, y=None):
        # Return a score indicating the success of your image generation
        # This could be based on the activation of the target class or other metrics
        return score

# Define the parameter distributions
param_distributions = {
    'blur_freq': [4, 5, 6],
    'blur_rad': [0.8, 1, 1.2],
    'wd': [0.0001, 0.001, 0.01, 0],
    'clipping_value': [0, 0.1, 0.2]
}

# Initialize RandomizedSearchCV
random_search = RandomizedSearchCV(estimator=ImageGeneratorEstimator(),
                                    param_distributions=param_distributions,
                                    n_iter=10,  # Number of parameter settings to try
                                    scoring='your_custom_scoring_function',
                                    cv=[(slice(None), slice(None))])  # Dummy split

X_dummy = np.zeros((1, 10))  
y_dummy = np.zeros(1)
# Execute the search
random_search.fit(X_dummy, y_dummy)  # You may need to pass dummy data here


InvalidParameterError: The 'scoring' parameter of RandomizedSearchCV must be a str among {'neg_mean_squared_log_error', 'completeness_score', 'neg_log_loss', 'neg_brier_score', 'accuracy', 'rand_score', 'matthews_corrcoef', 'neg_mean_absolute_error', 'f1_weighted', 'precision_micro', 'f1_samples', 'adjusted_mutual_info_score', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'average_precision', 'neg_mean_absolute_percentage_error', 'recall_weighted', 'roc_auc', 'neg_negative_likelihood_ratio', 'f1_micro', 'neg_root_mean_squared_error', 'neg_median_absolute_error', 'roc_auc_ovr_weighted', 'r2', 'roc_auc_ovr', 'precision_macro', 'jaccard_micro', 'f1', 'jaccard', 'jaccard_weighted', 'mutual_info_score', 'recall', 'jaccard_samples', 'top_k_accuracy', 'explained_variance', 'roc_auc_ovo_weighted', 'adjusted_rand_score', 'neg_mean_squared_error', 'positive_likelihood_ratio', 'normalized_mutual_info_score', 'recall_micro', 'precision_samples', 'balanced_accuracy', 'roc_auc_ovo', 'recall_macro', 'jaccard_macro', 'fowlkes_mallows_score', 'max_error', 'precision', 'precision_weighted', 'recall_samples', 'v_measure_score', 'homogeneity_score', 'f1_macro'}, a callable, an instance of 'list', an instance of 'tuple', an instance of 'dict' or None. Got 'your_custom_scoring_function' instead.